name: Validate e2e testing
description: "Runs e2e tests and validates e2e testing"

inputs:
  github-token:
    description: "GitHub Token for API access"
    required: true

runs:
  using: composite
  steps:
    - name: Restore cache Yarn
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/yarn
          node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    - name: Run tests e2e
      shell: bash
      run: yarn e2e
