name: Validate e2e testing
description: "Runs e2e tests and validates e2e testing"

inputs:
  github-token:
    description: "GitHub Token for API access"
    required: true

runs:
  using: composite
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.5.0
        token: ${{ inputs.github-token }}

    - name: Install dependencies
      shell: bash
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ inputs.github-token }}" > ./.npmrc
        yarn install --immutable-cache

    - name: Cache Yarn
      uses: actions/cache@v3
      with:
        path: .yarn/cache
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Run tests e2e
      shell: bash
      run: yarn e2e
