name: Validate linting
description: "Runs eslint and validates linting"

inputs:
  github-token:
    description: "GitHub Token for API access"
    required: true

runs:
  using: composite
  steps:
    - name: Install node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        token: ${{ inputs.github-token }}

    - name: Enable Corepack
      run: corepack enable

    - name: Setup Yarn Berry
      uses: threeal/setup-yarn-action@v2.0.0
      with:
        version: "4.x"

    - name: Install dependencies
      shell: bash
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ inputs.github-token }}" > ./.npmrc
        yarn cache clean
        yarn install --frozen-lockfile --network-concurrency 1

    - name: Cache Yarn
      uses: actions/cache@v3
      with:
        path: ~/.yarn/cache
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Run eslint
      shell: bash
      run: npx eslint --max-warnings=0
