name: Validate unit testing
description: "Runs unit tests and validates unit testing"

inputs:
  github-token:
    description: "GitHub Token for API access"
    required: true

runs:
  using: composite
  steps:
    - name: Restore cache Yarn
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/yarn
          node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    - name: Run tests
      shell: bash
      run: yarn test
