name: Validate unit testing
description: "Runs unit tests and validates unit testing"

inputs:
  github-token:
    description: "GitHub Token for API access"
    required: true

runs:
  using: composite
  steps:
    - name: Run tests
      shell: bash
      run: yarn test
