/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import primershopProductActions from "@primershop/strapi-plugin-product-actions/strapi-admin";
import primershopStatusManager from "@primershop/strapi-plugin-status-manager/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "primershop-product-actions": primershopProductActions,
    "primershop-status-manager": primershopStatusManager,
    "users-permissions": usersPermissions,
  },
});
