/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import primerProductActions from "@primer/strapi-plugin-product-actions/strapi-admin";
import primerStatusManager from "@primer/strapi-plugin-status-manager/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "primer-product-actions": primerProductActions,
    "primer-status-manager": primerStatusManager,
    "users-permissions": usersPermissions,
  },
});
