/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import statusManager from "../../src/plugins/status-manager/strapi-admin";
import productActions from "../../src/plugins/product-actions/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    seo: seo,
    "users-permissions": usersPermissions,
    "status-manager": statusManager,
    "product-actions": productActions,
  },
});
